-- Cached microstep decompositions generated by Claude at cook time.
-- Keyed by (recipe_id, servings) because scaled amounts are baked into the text.
-- Deleted automatically when the parent recipe is deleted (ON DELETE CASCADE)
-- and explicitly cleared when recipe steps are edited, so the cache never goes stale.
CREATE TABLE recipe_microsteps (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id  UUID        NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  servings   INTEGER     NOT NULL CHECK (servings >= 1 AND servings <= 20),
  steps      TEXT[]      NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (recipe_id, servings)
);
